include: package:lints/recommended.yaml

analyzer:
  errors:
    fixme: warning
    invalid_use_of_protected_member: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true